export const countries = [
    {"code": "gh", "name": "Ghana"},
    {"code": "dz", "name": "Algeria"},
    {"code": "ao", "name": "Angola"},
    {"code": "bj", "name": "Benin"},
    {"code": "bw", "name": "Botswana"},
    {"code": "bf", "name": "Burkina Faso"},
    {"code": "bi", "name": "Burundi"},
    {"code": "cv", "name": "Cabo Verde"},
    {"code": "cm", "name": "Cameroon"},
    {"code": "cf", "name": "Central African Republic"},
    {"code": "td", "name": "Chad"},
    {"code": "km", "name": "Comoros"},
    {"code": "cd", "name": "Congo, Democratic Republic of the"},
    {"code": "cg", "name": "Congo, Republic of the"},
    {"code": "ci", "name": "Côte d'Ivoire"},
    {"code": "dj", "name": "Djibouti"},
    {"code": "eg", "name": "Egypt"},
    {"code": "gq", "name": "Equatorial Guinea"},
    {"code": "er", "name": "Eritrea"},
    {"code": "sz", "name": "Eswatini"},
    {"code": "et", "name": "Ethiopia"},
    {"code": "ga", "name": "Gabon"},
    {"code": "gm", "name": "Gambia"},
    {"code": "gn", "name": "Guinea"},
    {"code": "gw", "name": "Guinea-Bissau"},
    {"code": "ke", "name": "Kenya"},
    {"code": "ls", "name": "Lesotho"},
    {"code": "lr", "name": "Liberia"},
    {"code": "ly", "name": "Libya"},
    {"code": "mg", "name": "Madagascar"},
    {"code": "mw", "name": "Malawi"},
    {"code": "ml", "name": "Mali"},
    {"code": "mr", "name": "Mauritania"},
    {"code": "mu", "name": "Mauritius"},
    {"code": "ma", "name": "Morocco"},
    {"code": "mz", "name": "Mozambique"},
    {"code": "na", "name": "Namibia"},
    {"code": "ne", "name": "Niger"},
    {"code": "ng", "name": "Nigeria"},
    {"code": "rw", "name": "Rwanda"},
    {"code": "st", "name": "São Tomé and Príncipe"},
    {"code": "sn", "name": "Senegal"},
    {"code": "sc", "name": "Seychelles"},
    {"code": "sl", "name": "Sierra Leone"},
    {"code": "so", "name": "Somalia"},
    {"code": "za", "name": "South Africa"},
    {"code": "ss", "name": "South Sudan"},
    {"code": "sd", "name": "Sudan"},
    {"code": "tz", "name": "Tanzania"},
    {"code": "tg", "name": "Togo"},
    {"code": "tn", "name": "Tunisia"},
    {"code": "ug", "name": "Uganda"},
    {"code": "zm", "name": "Zambia"},
    {"code": "zw", "name": "Zimbabwe"}

]