
export const endpoints ={
    login: 'auth/login',
    signup:"/auth/signup",
    fetch_user_wallet:"/wallets/wallet",
    fetch_sms_balance:"/sms-balance",
    top_up : '/sms-balance/purchase',
    sms_sender:"/sms-senders",
    send_sms :'sms/send',
    create_contact_single:"/contacts/single",
    create_contact_bulk:"/contacts/bulk",
    contacts:"/contacts",
    sms_history:"/sms/transactions",
    api_keys:"/api-keys",
    sms_templates:"/sms-templates",
    sms_summary:"/dashboard/sms-metrics",
    otp_history:"/otp/list",
    otp_summary:"/otp/summary",
    otp_generate_send:"/otp/generate-and-send-sms",
    otp_verify:"/otp/verify",
    wallet_transactions:"/wallets/all-transactions",
    sms_graph:"/dashboard/line-graph",
    sms_packages:"/sms-packages",
    wallets:"/wallets",
    wallet_topup:"/wallets/deposit/inline",
    transaction_verify:"/wallets/deposit/verify",
    groups:"/group",
    scheduleSms:"/scheduled-sms",
    generateAiMessage:"/sms/ai/generate",
    smsPackagePurchase:"/sms-package-purchases",
    admin_metrics:"/dashboard/admin-metrics",
    revenue_stats:"/dashboard/revenue",
    scheduled_sms:"/scheduled-sms",
    request_password_reset:"/auth/forgot-password",
    reset_password:"/auth/reset-password",
    top_up_user_wallet:"/admin/wallet/users",
    ussd_request:'/ussd-requests'
}